feat: add ci for prettier check and build
BuilderIO/gpt-crawler pull request #48
Opened 2023-11-21 18:47 UTC by kunal00000

Added CI for prettier check and build on PRs and pushes.
Resolves #47

2023-11-22 08:18 UTC, ManindraDeMel approved these changes

2023-11-22 14:05 UTC, marcelovicentegc commented on .github/workflows/build.yml
> +        run: npm run prettier:check
Static tests could run on git hooks/pre-commits as well along with a linter 😄

2023-11-26 19:05 UTC, kunal00000 commented on package.json
> +    "prettier": "^3.1.0"
Yeah sure.

2023-11-26 19:30 UTC, kunal00000 commented
I gave rebasing a shot, and I'm crossing my fingers that I got it right. 🧐 I always feel a bit on edge when I'm rebasing branches, especially when there are conflicts involved.

2023-11-26 20:31 UTC, steve8708 commented
apologies, we just merged a few more things, needs one more round of conflict resolution and then we can get this in!

2023-11-27 15:52 UTC, marcelovicentegc requested changes
I'm leaving a suggestion to open a new PR including only the changes for the prettier check step on CI since this PR duplicates the git history (per https://github.com/BuilderIO/gpt-crawler/pull/48#issuecomment-1828097212)

2023-11-28 13:43 UTC, closed without merging